[window]
opacity = 0.8

[font]
size = 11

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "MediumItalic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "MediumItalic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 5
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
